import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Regenerate the sign-in mail's inline assets as base64 string modules:
//   node scripts/email-assets.mjs   (from apps/web)
//
// Outputs (lib/src/email/assets/):
//   unbounded-800.ts  Unbounded 800 woff2, cyrillic + latin subsets, from
//                     @fontsource/unbounded — the package app/fonts.css uses.
//                     The mail embeds ONE subset (bg → cyrillic, en → latin)
//                     as a data-URI @font-face.
//   pops-mark.ts      pops-mark_240x200.png beside it: the coral mark, sent
//                     as an inline CID attachment and shown at 60×50.
//
// WHY MODULES, NOT FILES READ AT RUN TIME. The web container ships only
// .next/standalone, .next/static and public/ (Dockerfile). A file read from
// lib/ works under `next dev` and throws ENOENT in the container unless nft
// happened to trace it (lib/og/fonts.ts has the same story). A string constant
// is bundled like any other code.
//
// apps/web/tests/sign-in-mail.test.ts and lib/src/email/sign-in-mail.test.ts
// fail if a module drifts from its source, so re-run this after bumping
// @fontsource/unbounded or replacing the PNG.

const webRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const assetsDir = path.resolve(webRoot, '../../lib/src/email/assets');
const fontsource = path.join(webRoot, 'node_modules/@fontsource/unbounded');

const b64 = (file) => readFileSync(file).toString('base64');
const { version } = JSON.parse(readFileSync(path.join(fontsource, 'package.json'), 'utf8'));
const font = (subset) => b64(path.join(fontsource, `files/unbounded-${subset}-800-normal.woff2`));

const header = (lines) =>
  ['// GENERATED by apps/web/scripts/email-assets.mjs. Do not edit by hand.', ...lines].join('\n');

writeFileSync(
  path.join(assetsDir, 'unbounded-800.ts'),
  `${header([
    `// Source: @fontsource/unbounded ${version}, files/unbounded-{cyrillic,latin}-800-normal.woff2,`,
    '// byte for byte (apps/web/tests/sign-in-mail.test.ts holds it to that).',
  ])}

/** Unbounded 800 as base64 woff2, one subset per mail locale. */
export const UNBOUNDED_800_WOFF2 = {
  cyrillic:
    '${font('cyrillic')}',
  latin:
    '${font('latin')}',
} as const;
`,
);

writeFileSync(
  path.join(assetsDir, 'pops-mark.ts'),
  `${header([
    '// Source: pops-mark_240x200.png in this directory, byte for byte',
    '// (lib/src/email/sign-in-mail.test.ts holds it to that).',
  ])}

/** The coral POPS mark, a 240×200 transparent PNG shown at 60×50, as base64. */
export const POPS_MARK_PNG =
  '${b64(path.join(assetsDir, 'pops-mark_240x200.png'))}';
`,
);

console.log(`wrote unbounded-800.ts (@fontsource/unbounded ${version}) and pops-mark.ts`);
